### ISSUE TITLE
Error with Android

### ISSUE THREAD

**Issue by RevengeFNF** [quinton-ashley/cemu-no-gyro#1]
When i enter the link to access it with the Android phone, i get this:

`Error: Failed to lookup view "pug/client" in views directory "./views"
    at Function.render (C:\cemu-no-gyro-1.0.11-win\resources\app.asar\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (C:\cemu-no-gyro-1.0.11-win\resources\app.asar\node_modules\express\lib\response.js:1008:7)
    at C:\cemu-no-gyro-1.0.11-win\resources\app.asar\views\js\index.js:214:7
    at Layer.handle [as handle_request] (C:\cemu-no-gyro-1.0.11-win\resources\app.asar\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\cemu-no-gyro-1.0.11-win\resources\app.asar\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\cemu-no-gyro-1.0.11-win\resources\app.asar\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\cemu-no-gyro-1.0.11-win\resources\app.asar\node_modules\express\lib\router\layer.js:95:5)
    at C:\cemu-no-gyro-1.0.11-win\resources\app.asar\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\cemu-no-gyro-1.0.11-win\resources\app.asar\node_modules\express\lib\router\index.js:335:12)
    at next (C:\cemu-no-gyro-1.0.11-win\resources\app.asar\node_modules\express\lib\router\index.js:275:10)`

**Comment by JonathanPitre** [comment]
Same error here

**Comment by quinton-ashley** [comment]
Whoops, I used the wrong directory.  For some reason in development it worked though, very strange.  Fixed in v1.0.15
